# Classification Metrics

In this notebook, we will go through the most common classification metrics. This is a companion workbook for the 365 Data Science course on ML Process. This notebook only foucses on implementation. Check out the course or the documentation for the in-depth explanations of each approach.

We will cover:

- Accuracy, Precision, Recall
- F1-Score
- ROC-AUC
- PR-AUC
- Log Loss

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

## The Dataset

This dataset is a [marketing analytics dataset](https://www.kaggle.com/datasets/jackdaoud/marketing-data) around customer food preferences. Imagine you're a food company attempting to grow food purchases using a marketing campaign. 

In this dataset, we're going to build a propensity model. Propensity Models typically tell us a customer's propensity to make a purchase. Propensity models are useful for marketing teams to understand which users they should target. Then, they could save marketing $$ by making more targeted offers.

## Load Data

First, we'll load our dataset.

https://www.kaggle.com/datasets/sasivirat18/machine-learning-datasets

In [2]:
df = pd.read_csv(r"C:\Users\sasi virat\Downloads\learn-machine-learning-process-a-z\Section 12\10_Classification metrics - Coding portion\Course notes\ifood_df.csv")

We won't walk through each column in the dataset, but the dataset will contain variables describing the customer (education level, marital status etc..) and their past purchasing behavior (MntFish Products = amount spend on fish products).

In [3]:
df.head()

,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,...,marital_Together,marital_Widow,education_2n Cycle,education_Basic,education_Graduation,education_Master,education_PhD,MntTotal,MntRegularProds,AcceptedCmpOverall
0,58138.0,0,0,58,635,88,546,172,88,88,...,0,0,0,0,1,0,0,1529,1441,0
1,46344.0,1,1,38,11,1,6,2,1,6,...,0,0,0,0,1,0,0,21,15,0
2,71613.0,0,0,26,426,49,127,111,21,42,...,1,0,0,0,1,0,0,734,692,0
3,26646.0,1,0,26,11,4,20,10,3,5,...,1,0,0,0,1,0,0,48,43,0
4,58293.0,1,0,94,173,43,118,46,27,15,...,0,0,0,0,0,0,1,407,392,0

## Data Processing

To build a propensity model, we're going to try and predict whether a user *accepted any offer at all*. In order to make this prediction. we'll need to do some pre-processing:

In [4]:
cols = ['AcceptedCmp1',
       'AcceptedCmp2',
       'AcceptedCmp3',
       'AcceptedCmp4',
       'AcceptedCmp5',
       'AcceptedCmp']

## Create the target variable, if they accepted any campaign at all
df['AcceptedCmp'] = df['AcceptedCmp1'] + df['AcceptedCmp2'] + df['AcceptedCmp3'] + df['AcceptedCmp4'] + df['AcceptedCmp5']+ df['Response']

df['AcceptedCmp'] = np.where(df['AcceptedCmp'] > 0, 1, 0)

In [5]:
df[df['AcceptedCmp'] == 0]

,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,...,marital_Widow,education_2n Cycle,education_Basic,education_Graduation,education_Master,education_PhD,MntTotal,MntRegularProds,AcceptedCmpOverall,AcceptedCmp
1,46344.0,1,1,38,11,1,6,2,1,6,...,0,0,0,1,0,0,21,15,0,0
2,71613.0,0,0,26,426,49,127,111,21,42,...,0,0,0,1,0,0,734,692,0,0
3,26646.0,1,0,26,11,4,20,10,3,5,...,0,0,0,1,0,0,48,43,0,0
4,58293.0,1,0,94,173,43,118,46,27,15,...,0,0,0,0,0,1,407,392,0,0
5,62513.0,0,1,16,520,42,98,0,42,14,...,0,0,0,0,1,0,702,688,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2197,44802.0,0,0,71,853,10,143,13,10,20,...,0,0,0,0,1,0,1029,1009,0,0
2198,26816.0,0,0,50,5,1,6,3,4,3,...,0,0,0,1,0,0,19,16,0,0
2199,34421.0,1,0,81,3,3,7,6,2,9,...,0,0,0,1,0,0,21,12,0,0
2200,61223.0,0,1,46,709,43,182,42,118,247,...,0,0,0,1,0,0,1094,847,0,0
2203,69245.0,0,1,8,428,30,214,80,30,61,...,0,0,0,0,1,0,782,721,0,0

## Cross Validation

We'll do a simple train-test-split for cross validation:

In [7]:
from sklearn.model_selection import train_test_split

y = df['AcceptedCmp']
X = df.drop(cols,axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

## Model

Since the dataset is small, logistic regression would be the model of choice:

In [8]:
from sklearn.linear_model import LogisticRegression

rf = LogisticRegression()

rf.fit(X_train, y_train)
y_preds = rf.predict(X_test)

C:\Users\sasi virat\anaconda3\envs\DL_env\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

## Evaluation

### Accuracy, Precision, Recall

The simplest metrics are Accuracy/Precision/Recall. Here are the formulas:

`Accuracy`: (True Positives + True Negatives)/Total Predictions

`Precision`: True Positives/(True Positives + False Positives) 

`Recall`: True Positives/(True Positives + False Negatives)

In [16]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)


accuracy = accuracy_score(y_test, y_preds)
precision = precision_score(y_test, y_preds)
recall = recall_score(y_test, y_preds)


print("Accuracy: {0}".format(accuracy))
print("Precision: {0}".format(precision))
print("Recall: {0}".format(recall))

Accuracy: 0.7857142857142857
Precision: 0.6239316239316239
Recall: 0.3945945945945946

## F1-Score

F1-Score takes the harmonic mean of Precision and Recall. This is a good metric to use for imbalanced datasets. The formula looks like this: 

`F1-Score` = (2 x Precision x Recall)/(Precsion + Recall)

In [10]:
f1 = f1_score(y_test, y_preds)
print("F1: {0}".format(f1))

F1: 0.48344370860927155

### ROC-AUC

ROC-AUC evaluates the tradeoff between the True Positive Rate and the False Positive Rate. To review, the formulas are: 

`True Positive Rate` = True Positives/Actual Positives

`False Positive Rate` = False Positives/Actual Negatives

It tells us how well we're able to separate two classes in our predictions:

In [12]:
from sklearn.metrics import (
    roc_auc_score,
    average_precision_score
)


roc_auc = roc_auc_score(y_test, y_preds)

print("ROC-AUC: {0}".format(roc_auc))

ROC-AUC: 0.656781643521975

### PR-AUC

PR-AUC behaves similar to ROC-AUC, except we're evaluating the tradeoff between Precision and Recall, hence (PR - AUC):

In [14]:
from sklearn.metrics import (
    average_precision_score
)

pr_auc = average_precision_score(y_test, y_preds)

print("PR-AUC: {0}".format(pr_auc))

PR-AUC: 0.40004620004620006

### Log Loss

The intuition behind log loss is that weâ€™re measuring how close our predicted probability is to the true value. Log Loss will penalize errors exponentially:

In [15]:
from sklearn.metrics import (
    log_loss
)

log_loss = log_loss(y_test, y_preds)

print("Log Loss: {0}".format(log_loss))

Log Loss: 7.401214697655214

## Conclusion

In review, we went over a variety of regression metrics:

- Accuracy, Precision, Recall
- F1-Score
- ROC-AUC
- PR-UC
- Log Loss

## Additional Resources
- [Model Evaluation Metrics in Machine Learning by Nagesh Singh Chauhan](https://www.kdnuggets.com/2020/05/model-evaluation-metrics-machine-learning.html)
- [11 Important Model Evaluation Metrics for Machine Learning Everyone should know](https://www.analyticsvidhya.com/blog/2019/08/11-important-model-evaluation-error-metrics/)
- [How To Interpret R-squared in Regression Analysis by Jim Frost](https://statisticsbyjim.com/regression/interpret-r-squared-regression/)
- [Know The Best Evaluation Metrics for Your Regression Model by Raghav Agrawal](https://www.analyticsvidhya.com/blog/2021/05/know-the-best-evaluation-metrics-for-your-regression-model/)
- [Recall, Precision, F1, ROC, AUC, and everything by Ofir Shalev](https://medium.com/swlh/recall-precision-f1-roc-auc-and-everything-542aedf322b9)
- [F1 Score vs ROC AUC vs Accuracy vs PR AUC: Which Evaluation Metric Should You Choose? by Jakub Czakon](https://neptune.ai/blog/f1-score-accuracy-roc-auc-pr-auc)
- [Intuition behind Log Loss Score by Gaurav Dembla](https://towardsdatascience.com/intuition-behind-log-loss-score-4e0c9979680a#:~:text=is%20dependent%20on.-,What%20does%20log%2Dloss%20conceptually%20mean%3F,is%20the%20log%2Dloss%20value.)
- [Why is ROC AUC equivalent to the probability that two randomly-selected samples are correctly ranked?](https://stats.stackexchange.com/questions/190216/why-is-roc-auc-equivalent-to-the-probability-that-two-randomly-selected-samples)
- [Man U Whitney Test](https://en.wikipedia.org/wiki/Mann%E2%80%93Whitney_U_test#Area-under-curve_(AUC)_statistic_for_ROC_curves)
- [Essential Things You Need to Know About F1-Score](https://en.wikipedia.org/wiki/Mann%E2%80%93Whitney_U_test#Area-under-curve_(AUC)_statistic_for_ROC_curves)
- [ROC, AUC, precision, and recall visually explained by Paul Vanderlaken](https://paulvanderlaken.com/2019/08/16/roc-auc-precision-and-recall-visually-explained/)
- [R-squared Is Not Valid for Nonlinear Regression by Jim Frost](https://statisticsbyjim.com/regression/r-squared-invalid-nonlinear-regression/#:~:text=Nonlinear%20regression%20is%20an%20extremely,just%20don%27t%20go%20together.)
- [3 Best metrics to evaluate Regression Model? by Songhao Wu](https://towardsdatascience.com/what-are-the-best-metrics-to-evaluate-your-regression-model-418ca481755b)